version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/src/graphql.server.link"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/dev/graphql.dev.chat.ui"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-redux
    versions:
    - "> 5.1.1"
  - dependency-name: "@types/react-redux"
    versions:
    - "> 6.0.13"
