using Tanka.GraphQL.Server;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.AddTankaGraphQL()
    .AddHttp()
    .AddWebSockets()
    .AddSchemaOptions("Default", options =>
    {
        // This extension point is used by the generator to add
        // type controllers
        options.AddGeneratedTypes(types =>
        {
            // This method is generated by the generator from Query class
            types.AddQueryController();

            // This method is generated by the generator from World class
            types.AddWorldController();

            //todo: generate namespace specific method for adding all types in namespace
        });
    });

WebApplication? app = builder.Build();
app.UseWebSockets();

app.MapTankaGraphQL("/graphql", "Default");
app.Run();

/// <summary>
///     Root query type by naming convention
///     <remarks>
///         We define it as static class so that the generator does not try
///         to use the initialValue as the source of it.
///     </remarks>
/// </summary>
[ObjectType]
public static class Query
{
    public static World World() => new();
}

[ObjectType]
public class World
{
    /// <summary>
    ///     Simple field with one string argument and string return type
    /// </summary>
    /// <param name="name">name: String!</param>
    /// <returns>String!</returns>
    public string Hello(string name) => $"Hello {name}";
}