//HintName: InputMessageInputType.g.cs
/// <auto-generated/>

#nullable enable
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using Tanka.GraphQL.Server;
using Tanka.GraphQL.Executable;
using Tanka.GraphQL.ValueResolution;
using Tanka.GraphQL.Fields;

public static class InputMessageInputTypeExtensions
{
    public static SourceGeneratedTypesBuilder AddInputMessageInputType(this SourceGeneratedTypesBuilder builder)
    {
        builder.Builder.Configure(options => options.Builder.Add("""
                input InputMessage
                {
                    content: Int
                }
                """));
        return builder;
    }
}

public partial class InputMessage : IParseableInputObject
{
    public void Parse(IReadOnlyDictionary<string, object?> argumentValue)
    {
        // Content is an scalar type
        if (argumentValue.TryGetValue("content", out var contentValue))
        {
            Content = contentValue as int;
        }
    }
}
#nullable restore
