//HintName: TestsIValueController.g.cs
/// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Options;
using System;
using System.Threading.Tasks;
using Tanka.GraphQL.Executable;
using Tanka.GraphQL.Fields;
using Tanka.GraphQL.Server;
using Tanka.GraphQL.TypeSystem;
using Tanka.GraphQL.ValueResolution;

namespace Tests;

public static class IValueControllerExtensions
{
    public static SourceGeneratedTypesBuilder AddIValueController(
        this SourceGeneratedTypesBuilder builder)
    {
        builder.Builder.Configure(options => options.Builder.Add(
            """
            interface IValue
            {
                hello: String!
            }
            """));

        return builder;
    }
}

public partial interface IValue: INamedType
{
    public string __Typename => "IValue";
}

#nullable restore