//HintName: TestsSubscriptionController.g.cs
/// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Options;
using System;
using System.Threading.Tasks;
using Tanka.GraphQL.Executable;
using Tanka.GraphQL.Fields;
using Tanka.GraphQL.Server;
using Tanka.GraphQL.TypeSystem;
using Tanka.GraphQL.ValueResolution;

namespace Tests;

public static class SubscriptionController
{
    public static ValueTask ResolveRandom(ResolverContext context)
    {
        context.ResolvedValue = context.ObjectValue;
        
        return default;
    }
    
    public static ValueTask Random(SubscriberContext context, CancellationToken cancellationToken)
    {
        context.SetResult(Subscription.Random(
            context.GetArgument<int>("from"),
            context.GetArgument<int>("to"),
            cancellationToken
            ));
        
        return default;
    }
}

public static class SubscriptionControllerExtensions
{
    public static SourceGeneratedTypesBuilder AddSubscriptionController(
        this SourceGeneratedTypesBuilder builder)
    {
        builder.Builder.Configure(options => options.Builder.Add(
            "Subscription",
            new FieldsWithResolvers()
            {
                { "random(from: Int!, to: Int!): Int!", SubscriptionController.ResolveRandom }
            }
            ));

        return builder;
    }
}

public partial class Subscription: INamedType
{
    public string __Typename => "Subscription";
}

#nullable restore