//HintName: TestsStringValueController.g.cs
/// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Options;
using System;
using System.Threading.Tasks;
using Tanka.GraphQL.Executable;
using Tanka.GraphQL.Fields;
using Tanka.GraphQL.Server;
using Tanka.GraphQL.TypeSystem;
using Tanka.GraphQL.ValueResolution;

namespace Tests;

public static partial class StringValueController
{
    public static ValueTask Value(ResolverContext context)
    {
        context.ResolvedValue = ((StringValue)context.ObjectValue).Value;
        return default;
    }

    public static ValueTask Hello(ResolverContext context)
    {
        context.ResolvedValue = ((StringValue)context.ObjectValue).Hello;
        return default;
    }
}

public static class StringValueControllerExtensions
{
    public static SourceGeneratedTypesBuilder AddStringValueController(
        this SourceGeneratedTypesBuilder builder)
    {
        builder.Builder.Configure(options => options.Builder.Add(
            "StringValue",
            new FieldsWithResolvers()
            {
                { "value: String!", StringValueController.Value },
                { "hello: String!", StringValueController.Hello }
            }            ));
            
        builder.Builder.Configure(options => options.Builder.Add(
            """
            extend type StringValue implements IValue
            """));
            
        return builder;
    }
}

public partial class StringValue: INamedType
{
    public string __Typename => "StringValue";
}

#nullable restore