//HintName: TestsSubscriptionController.g.cs
/// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Options;
using System;
using System.Threading.Tasks;
using Tanka.GraphQL.Executable;
using Tanka.GraphQL.Fields;
using Tanka.GraphQL.Server;
using Tanka.GraphQL.TypeSystem;
using Tanka.GraphQL.ValueResolution;

namespace Tests;

public static partial class SubscriptionController
{
    public static ValueTask ResolveRandom(ResolverContext context)
    {
        BeforeResolveRandom(context);
        
        context.ResolvedValue = context.ObjectValue;
        AfterResolveRandom(context);
        return default;
    }
    
    public static ValueTask Random(SubscriberContext context, CancellationToken cancellationToken)
    {
        BeforeRandom(context);
        
        context.SetResult(Subscription.Random(
            context.GetArgument<int>("from"),
            context.GetArgument<int>("to"),
            cancellationToken
            ));
        
        AfterRandom(context);
        return default;
    }
    
    partial void BeforeRandom(SubscriberContext context);
    partial void AfterRandom(SubscriberContext context);
    partial void BeforeResolveRandom(ResolverContext context);
    partial void AfterResolveRandom(ResolverContext context);
}

public static class SubscriptionControllerExtensions
{
    public static SourceGeneratedTypesBuilder AddSubscriptionController(
        this SourceGeneratedTypesBuilder builder)
    {
        builder.Builder.Configure(options => options.Builder.Add(
            "Subscription",
            new FieldsWithResolvers()
            {
                { "random(from: Int!, to: Int!): Int!", SubscriptionController.ResolveRandom }
            }, 
            new FieldsWithSubscribers()
            {
                { "random(from: Int!, to: Int!): Int!", SubscriptionController.Random }
            }
            ));

        return builder;
    }
}

public static partial class Subscription
{
    public static string __Typename => "Subscription";
}

#nullable restore