//HintName: TestsWorldController.g.cs
/// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Options;
using System;
using System.Threading.Tasks;
using Tanka.GraphQL.Executable;
using Tanka.GraphQL.Fields;
using Tanka.GraphQL.Server;
using Tanka.GraphQL.TypeSystem;
using Tanka.GraphQL.ValueResolution;

namespace Tests;

public static partial class WorldController
{
    public static ValueTask ResolveRandom(ResolverContext context)
    {
        BeforeResolveRandom(context);
        
        context.ResolvedValue = context.ObjectValue;
        AfterResolveRandom(context);
        return default;
    }
    
    public static ValueTask Random(SubscriberContext context, CancellationToken cancellationToken)
    {
        BeforeRandom(context);
        
        context.SetResult(((World)context.ObjectValue).Random(
            context.GetArgument<int>("from"),
            context.GetArgument<int>("to"),
            context.GetArgument<int>("count"),
            cancellationToken
            ));
        
        AfterRandom(context);
        return default;
    }
    
    static partial void BeforeRandom(SubscriberContext context);
    static partial void AfterRandom(SubscriberContext context);
    static partial void BeforeResolveRandom(ResolverContext context);
    static partial void AfterResolveRandom(ResolverContext context);
}

public static class WorldControllerExtensions
{
    public static SourceGeneratedTypesBuilder AddWorldController(
        this SourceGeneratedTypesBuilder builder)
    {
        builder.Builder.Configure(options => options.Builder.Add(
            "World",
            new FieldsWithResolvers()
            {
                { "random(from: Int!, to: Int!, count: Int!): Int!", WorldController.ResolveRandom }
            }, 
            new FieldsWithSubscribers()
            {
                { "random(from: Int!, to: Int!, count: Int!): Int!", WorldController.Random }
            }
            ));

        return builder;
    }
}

public partial class World: INamedType
{
    public string __Typename => "World";
}

#nullable restore