//HintName: PersonController.g.cs
/// <auto-generated/>
#nullable enable

using Microsoft.Extensions.Options;
using System;
using System.Threading.Tasks;
using Tanka.GraphQL.Executable;
using Tanka.GraphQL.Fields;
using Tanka.GraphQL.Server;
using Tanka.GraphQL.TypeSystem;
using Tanka.GraphQL.ValueResolution;


public static partial class PersonController
{
    public static ValueTask Name(ResolverContext context)
    {
        context.ResolvedValue = ((Person)context.ObjectValue).Name;
        return default;
    }
}

public static class PersonControllerExtensions
{
    public static SourceGeneratedTypesBuilder AddPersonController(
        this SourceGeneratedTypesBuilder builder)
    {
        builder.Builder.Configure(options => options.Builder.Add(
            "Person",
            new FieldsWithResolvers()
            {
                { "name: String!", PersonController.Name }
            }            ));

        return builder;
    }
}

public partial class Person: INamedType
{
    public string __Typename => "Person";
}

#nullable restore