//HintName: TestsQueryController.g.cs
/// <auto-generated/>

#nullable enable
using Microsoft.Extensions.Options;
using System;
using System.Threading.Tasks;
using Tanka.GraphQL.Executable;
using Tanka.GraphQL.Fields;
using Tanka.GraphQL.Server;
using Tanka.GraphQL.ValueResolution;

namespace Tests;
public static class QueryController
{
    public static ValueTask World(ResolverContext context)
    {
        context.ResolvedValue = Query.World();
        return default;
    }
}

public static class QueryControllerExtensions
{
    public static SourceGeneratedTypesBuilder AddQueryController(this SourceGeneratedTypesBuilder builder)
    {
        builder.Builder.Configure(options => options.Builder.Add("Query", new FieldsWithResolvers() { { "world: World!", QueryController.World } }));
        return builder;
    }
}
#nullable restore
