federation_version: =2.7.8
subgraphs:
  inventory:
    routing_url: http://inventory:4003
    schema:
      file: ./federation-tests/dist/subgraphs/inventory/inventory.graphql
  users:
    routing_url: http://users:4002
    schema:
      file: ./federation-tests/dist/subgraphs/users/users.graphql
  products:
    routing_url: http://products:4001
    schema:
      file: products.graphql
