name: Build docs

on:
  push:
    branches:
      - main
      - release/**
    tags:
      - '*'
  pull_request:
    branches: [main]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build docs
        shell: pwsh
        run: |
          ./build-docs.ps1 -Output ./artifacts/gh-pages -CurrentBranch $Env:GITHUB_REF_NAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        if: github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/')
        with:
          branch: gh-pages
          folder: ./artifacts/gh-pages
          commit-message: ${{github.ref_name}}
          clean: true
