name: Build and package

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
      - release/**
    tags:
      - "*"
  pull_request:
    branches: [master]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build packages
        shell: pwsh
        run: |
          ./build.ps1 -Output ./artifacts -CurrentBranch $Env:GITHUB_REF_NAME

      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: |
            ./artifacts/*.nupkg
            ./artifacts/*.tgz

      - name: Publish to nuget
        if: github.ref_name == 'master' || startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          dotnet nuget push "./artifacts/*.nupkg" -k $Env:NUGET_KEY -s https://api.nuget.org/v3/index.json

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish beta NPM package
        if: github.ref_name == 'master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
        working-directory: ./artifacts/graphql.server.link
        run: npm publish --tag beta

      - name: Publish release NPM package
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
        working-directory: ./artifacts/graphql.server.link
        run: npm publish
